title: Richard Guilherme - Portfólio de Data Science
author: Richard Guilherme
url: https://zheage.github.io/richardguilherme.github.io/ # root address of the site
description:  # description of the site (multiple lines allowed)

Atualmente é consultor de estatística na empresa StepWise, realizando análise e modelagem
de dados para auxiliar na tomada de decisão. Realiza pesquisa como aluno do programa de
mestrado PIPGEs da USP e UFSCar de São Carlos na área de aprendizado de máquina,
focando em métodos de predição de eventos raros, buscando soluções em problemas
comuns que acontecem na elaboração de modelos no mercado financeiro.
Possui conhecimentos em Python, R, SQL e Excel, assim como em suas principais bibliotecas
de análise e visualização de dados como pandas, numpy, matplotlib, seaborn, sklearn e
tidyverse.


permalink: /:slug

favicon: "./logo.png" # relative path to site's favicon


#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  back_home_text: "home.." # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: true # show blog description
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  show_copyright: true # show copyright notice in footer
  # following keys are using to create home layout
  show_projects: true # show projects as cards, add in _data/home.yml
  show_blog: true # show blog posts added in _posts
  show_old_projects: false # show old projects as cards, add in _data/home.yml
  show_misc_list: false # show generic vertical list for misc details, add _data/home.yml
  show_reading_time: true # show number of words and reading time in the blog posts
  show_tags: false # show tags in a blog posts
  # options for "home" page 
  home:
    title_projects: Portfólio
    title_misc_list: Details
    title_blog: Artigos
    title_old_projects: Projetos Antigos

soopr:
  publish_token: "" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

highlighter: monokai # rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
